version: '3.8'
services:
  frontend:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run build && npm run start"
    env_file:
      - .env.local
    ports:
      - "3003:3000"
