version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inlaze
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
