version: '3.8'
services:
  notifications:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run build && npm run start:prod"
    env_file:
      - .env
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
